Задание 1.

In [146]:
import numpy as np

In [147]:
a = np.linspace(12, 23, 12)
a

array([12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.])

Задание 2.

In [148]:
a1 = a.reshape(2, 6)
a1

array([[12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.]])

In [149]:
a2 = a.reshape(3, 4)
a2

array([[12., 13., 14., 15.],
       [16., 17., 18., 19.],
       [20., 21., 22., 23.]])

In [150]:
a3 = a.reshape(4, 3)
a3

array([[12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.]])

In [151]:
a4 = a.reshape(6, 2)
a4

array([[12., 13.],
       [14., 15.],
       [16., 17.],
       [18., 19.],
       [20., 21.],
       [22., 23.]])

In [152]:
a5 = a.reshape(12, 1)
a5

array([[12.],
       [13.],
       [14.],
       [15.],
       [16.],
       [17.],
       [18.],
       [19.],
       [20.],
       [21.],
       [22.],
       [23.]])

In [153]:
a1 = a.reshape(2, -1)
a1

array([[12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.]])

In [154]:
a1 = a.reshape(3, -1)
a1

array([[12., 13., 14., 15.],
       [16., 17., 18., 19.],
       [20., 21., 22., 23.]])

In [155]:
a1 = a.reshape(4, -1)
a1

array([[12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.]])

In [156]:
a1 = a.reshape(-1, 6)
a1

array([[12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.]])

In [157]:
a1 = a.reshape(-1, 12)
a1

array([[12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.]])

Задание 4

Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

Думаю, что нет

Задание 5

In [158]:
a = np.random.randn(3, 4)
a

array([[-0.62947496,  0.59772047,  2.55948803,  0.39423302],
       [ 0.12221917, -0.51543566, -0.60025385,  0.94743982],
       [ 0.291034  , -0.63555974, -1.02155219, -0.16175539]])

In [159]:
a.size

12

In [160]:
b = a.reshape(1, -1)
b

array([[-0.62947496,  0.59772047,  2.55948803,  0.39423302,  0.12221917,
        -0.51543566, -0.60025385,  0.94743982,  0.291034  , -0.63555974,
        -1.02155219, -0.16175539]])

In [161]:
b.size

12

Задание 6

In [162]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

Задание 7

In [163]:
b = np.arange(20, 1, -2)
b

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

В чем разница a и b  - не могу ответить. 

Задание 8

In [164]:
a = np.zeros((2, 2))
a

array([[0., 0.],
       [0., 0.]])

In [165]:
b = np.ones((3, 2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [166]:
v = np.concatenate((a, b), axis=0)
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [167]:
v.size

10

Задание 9

In [168]:
a = np.arange(12)

a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [169]:
A = a.reshape(4, 3)

A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [170]:
At = A.T

At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [171]:
B = A.dot(At)

B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [172]:
B.size

16

In [173]:
d = np.linalg.det(B)
print ('Определитель матрицы:', d)

Определитель матрицы: 0.0


Т.к. определитель равен 0, то обратную матрицу для B нельзя вычислить

Задание 10

In [174]:
import random

In [175]:
np.random.seed(42)
np.random.random(5)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

Задание 11

Не понимаю суть задания. Как могут числа быть СЛУЧАЙНЫМИ и одновременно РАВНОМЕРНО распределенными в четко заданном промежутке

In [176]:
c = np.linspace(0, 15, 16)

c

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15.])

Задавние 12

In [177]:
C = c.reshape(4, 4)

C

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [178]:
D = np.add(B, np.dot(C, 10))

D

array([[  5.,  24.,  43.,  62.],
       [ 54., 100., 146., 192.],
       [103., 176., 249., 322.],
       [152., 252., 352., 452.]])

In [179]:
d = np.linalg.det(D)
print ('Определитель матрицы D:', d)

Определитель матрицы D: -7.685903354004529e-25


In [180]:
r = np.linalg.matrix_rank(D)
print ('Ранг матрицы D:', r)

Ранг матрицы D: 2


In [181]:
D_inv = np.linalg.inv(D)
print ('Обратная матрица:', D_inv)

Обратная матрица: [[ 1.10382344e+13  5.26315789e-02 -3.31147031e+13  2.20764688e+13]
 [-8.46264636e+13  9.38249922e+13  6.62294063e+13 -7.54279349e+13]
 [ 1.36138224e+14 -1.87649984e+14 -3.31147031e+13  8.46264636e+13]
 [-6.25499948e+13  9.38249922e+13  0.00000000e+00 -3.12749974e+13]]


Задание 13

Данное задание довел до этапа:

"С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4."

А дальше не получилось сделать

In [182]:
D_inv

array([[ 1.10382344e+13,  5.26315789e-02, -3.31147031e+13,
         2.20764688e+13],
       [-8.46264636e+13,  9.38249922e+13,  6.62294063e+13,
        -7.54279349e+13],
       [ 1.36138224e+14, -1.87649984e+14, -3.31147031e+13,
         8.46264636e+13],
       [-6.25499948e+13,  9.38249922e+13,  0.00000000e+00,
        -3.12749974e+13]])

In [183]:
D_inv[D_inv < 0] = 0

D_inv

array([[1.10382344e+13, 5.26315789e-02, 0.00000000e+00, 2.20764688e+13],
       [0.00000000e+00, 9.38249922e+13, 6.62294063e+13, 0.00000000e+00],
       [1.36138224e+14, 0.00000000e+00, 0.00000000e+00, 8.46264636e+13],
       [0.00000000e+00, 9.38249922e+13, 0.00000000e+00, 0.00000000e+00]])

In [184]:
D_inv[D_inv > 0] = 1

D_inv

array([[1., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 0., 0.]])

Убедимся, что в матрице D_inv остались только нули и единицы.

In [187]:
np.count_nonzero(D_inv > 1)

0

In [188]:
np.count_nonzero(D_inv < 0)

0

In [207]:
D_inv

array([[1., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 0., 0.]])

In [191]:
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [192]:
C

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])